import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class MenuItem extends ContentItem {
  public price!: Elements.TextElement;
  public name!: Elements.TextElement;
  public notes!: Elements.TextElement;
  public description!: Elements.RichTextElement;
}
